name: scp maps
on: 
  push:
    branches:
      - master
jobs:
  DeployMaps:
    name: Map Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LOWORBITHOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "voting.json"
        target: "~/containers/eldewrito/cache/"
        overwrite: 1
        
  DeployVoteConfig:
    name: Map Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LOWORBITHOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "voting.json"
        target: "~/containers/eldewrito/cache/"
        overwrite: 1
